# Generated by Django 5.2 on 2025-05-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AminoAcid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('three_letter_code', models.CharField(max_length=3)),
                ('one_letter_code', models.CharField(max_length=1)),
                ('structure_image', models.ImageField(upload_to='structures/')),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
